name: Generate Stats Images

on:
    schedule: # Schedule updates (each 6 hours)
        - cron: '5 */6 * * *'
    workflow_dispatch:

permissions:
    contents: write

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Clone github-stats
              run: |
                  git clone https://github.com/auioc/github-stats.git

            - name: Set up Python 3.8
              uses: actions/setup-python@v5
              with:
                  python-version: '3.8'
                  architecture: 'x64'
                  cache: 'pip'

            - name: Install requirements
              run: |
                  python3 -m pip install --upgrade pip setuptools wheel
                  python3 -m pip install -r github-stats/requirements.txt

            - name: Generate images
              run: |
                  python3 --version
                  cd github-stats
                  python3 generate_images.py
                  cp -r generated ../
              env:
                  USERNAME: ${{ secrets.USERNAME }}
                  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                  #   EXCLUDED_REPOS: ${{ secrets.EXCLUDED_REPOS }}
                  #   EXCLUDED_LANGS: ${{ secrets.EXCLUDED_LANGS }}
                  INCLUDED_OWNERS: ${{ secrets.INCLUDED_OWNERS }}

            - name: Commit to the repo
              run: |
                  git config --global user.name "github-actions[bot]"
                  git config --global user.email "github-actions[bot]@users.noreply.github.com"
                  git add .
                  # Force the build to succeed, even if no files were changed
                  git commit -m 'Update generated files' || true
                  git push
